cargo-features = []

[workspace]
resolver = "3"
members = ["foo-user", "foo"]

[workspace.package]
edition = "2024"
rust-version = "1.85"
version = "0.0.1"

[workspace.dependencies]
# verus
vstd = { git = "https://github.com/verus-lang/verus", branch = "main" }
verus_builtin = { git = "https://github.com/verus-lang/verus", branch = "main" }
verus_builtin_macros = { git = "https://github.com/verus-lang/verus", branch = "main" }

foo = { path = "foo" }

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(verus_keep_ghost)'] }
