[package]
name = "foo-user"
description = "thing that uses the foo library"

edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
# verus
vstd = { workspace = true }
verus_builtin = { workspace = true }
verus_builtin_macros = { workspace = true }
# foo
foo = { workspace = true }

[lints]
workspace = true

[package.metadata.verus]
verify = true
